server:
  port: 8081
  servlet:
    context-path: /zone
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/test2?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: admin_123
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath:com/zone/modular/**/mapper/xml/*.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
